<?php
/**
 * InvoiceRequestV2Model
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Capayable API V2
 *
 * API for Pay after delivery and Pay in 3 installments
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

//namespace Swagger\Client\Model;

//use \ArrayAccess;

/**
 * InvoiceRequestV2Model Class Doc Comment
 *
 * @category    Class */
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Tritacv2_Model_InvoiceRequestV2Model implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'InvoiceRequestV2Model';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'transaction_number'        => 'string',
        'invoice_number'            => 'string',
        'invoice_date'              => '\DateTime',
        'invoice_amount'            => 'int',
        'invoice_description'       => 'string',
        'invoice_pdf_submit_type'   => 'string',
        'invoice_pdf_url'           => 'string',
        'invoice_pdf_email_sent_date' => '\DateTime',
        'invoice_pdf_from_email'    => 'string',
        'invoice_pdf_email_subject' => 'string',
        'extra_info'                => 'string',
        'culture_code'              => 'string',
        'invoice_pdf_data'          => 'Tritacv2_Model_InvoicePdfDataModel' //'\Swagger\Client\Model\InvoicePdfDataModel'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'transaction_number'        => 'TransactionNumber',
        'invoice_number'            => 'InvoiceNumber',
        'invoice_date'              => 'InvoiceDate',
        'invoice_amount'            => 'InvoiceAmount',
        'invoice_description'       => 'InvoiceDescription',
        'invoice_pdf_submit_type'   => 'InvoicePdfSubmitType',
        'invoice_pdf_url'           => 'InvoicePdfUrl',
        'invoice_pdf_email_sent_date' => 'InvoicePdfEmailSentDate',
        'invoice_pdf_from_email'    => 'InvoicePdfFromEmail',
        'invoice_pdf_email_subject' => 'InvoicePdfEmailSubject',
        'extra_info'                => 'ExtraInfo',
        'culture_code'              => 'CultureCode',
        'invoice_pdf_data'          => 'InvoicePdfData'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'transaction_number'        => 'setTransactionNumber',
        'invoice_number'            => 'setInvoiceNumber',
        'invoice_date'              => 'setInvoiceDate',
        'invoice_amount'            => 'setInvoiceAmount',
        'invoice_description'       => 'setInvoiceDescription',
        'invoice_pdf_submit_type'   => 'setInvoicePdfSubmitType',
        'invoice_pdf_url'           => 'setInvoicePdfUrl',
        'invoice_pdf_email_sent_date' => 'setInvoicePdfEmailSentDate',
        'invoice_pdf_from_email'    => 'setInvoicePdfFromEmail',
        'invoice_pdf_email_subject' => 'setInvoicePdfEmailSubject',
        'extra_info'                => 'setExtraInfo',
        'culture_code'              => 'setCultureCode',
        'invoice_pdf_data'          => 'setInvoicePdfData'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'transaction_number'        => 'getTransactionNumber',
        'invoice_number'            => 'getInvoiceNumber',
        'invoice_date'              => 'getInvoiceDate',
        'invoice_amount'            => 'getInvoiceAmount',
        'invoice_description'       => 'getInvoiceDescription',
        'invoice_pdf_submit_type'   => 'getInvoicePdfSubmitType',
        'invoice_pdf_url'           => 'getInvoicePdfUrl',
        'invoice_pdf_email_sent_date' => 'getInvoicePdfEmailSentDate',
        'invoice_pdf_from_email'    => 'getInvoicePdfFromEmail',
        'invoice_pdf_email_subject' => 'getInvoicePdfEmailSubject',
        'extra_info'                => 'getExtraInfo',
        'culture_code'              => 'getCultureCode',
        'invoice_pdf_data'          => 'getInvoicePdfData'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const INVOICE_PDF_SUBMIT_TYPE_URL           = 'URL';
    const INVOICE_PDF_SUBMIT_TYPE_BCC_EMAIL     = 'BCC_EMAIL';
    const INVOICE_PDF_SUBMIT_TYPE_INCLUDED_DATA = 'INCLUDED_DATA';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getInvoicePdfSubmitTypeAllowableValues()
    {
        return [
            self::INVOICE_PDF_SUBMIT_TYPE_URL,
            self::INVOICE_PDF_SUBMIT_TYPE_BCC_EMAIL,
            self::INVOICE_PDF_SUBMIT_TYPE_INCLUDED_DATA,
        ];
    }

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['transaction_number']      = isset($data['transaction_number']) ? $data['transaction_number'] : null;
        $this->container['invoice_number']          = isset($data['invoice_number']) ? $data['invoice_number'] : null;
        $this->container['invoice_date']            = isset($data['invoice_date']) ? $data['invoice_date'] : null;
        $this->container['invoice_amount']          = isset($data['invoice_amount']) ? $data['invoice_amount'] : null;
        $this->container['invoice_description']     = isset($data['invoice_description']) ? $data['invoice_description'] : null;
        $this->container['invoice_pdf_submit_type'] = isset($data['invoice_pdf_submit_type']) ? $data['invoice_pdf_submit_type'] : null;
        $this->container['invoice_pdf_url']         = isset($data['invoice_pdf_url']) ? $data['invoice_pdf_url'] : null;
        $this->container['invoice_pdf_email_sent_date'] = isset($data['invoice_pdf_email_sent_date']) ? $data['invoice_pdf_email_sent_date'] : null;
        $this->container['invoice_pdf_from_email']  = isset($data['invoice_pdf_from_email']) ? $data['invoice_pdf_from_email'] : null;
        $this->container['invoice_pdf_email_subject'] = isset($data['invoice_pdf_email_subject']) ? $data['invoice_pdf_email_subject'] : null;
        $this->container['extra_info']              = isset($data['extra_info']) ? $data['extra_info'] : null;
        $this->container['culture_code']            = isset($data['culture_code']) ? $data['culture_code'] : null;
        $this->container['invoice_pdf_data']        = isset($data['invoice_pdf_data']) ? $data['invoice_pdf_data'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];
        if ($this->container['transaction_number'] === null) {
            $invalid_properties[] = "'transaction_number' can't be null";
        }
        if ((strlen($this->container['transaction_number']) > 32)) {
            $invalid_properties[] = "invalid value for 'transaction_number', the character length must be smaller than or equal to 32.";
        }

        if ((strlen($this->container['transaction_number']) < 0)) {
            $invalid_properties[] = "invalid value for 'transaction_number', the character length must be bigger than or equal to 0.";
        }

        if (!preg_match("/[a-fA-F0-9]{32}/", $this->container['transaction_number'])) {
            $invalid_properties[] = "invalid value for 'transaction_number', must be conform to the pattern /[a-fA-F0-9]{32}/.";
        }

        if ($this->container['invoice_number'] === null) {
            $invalid_properties[] = "'invoice_number' can't be null";
        }
        if ((strlen($this->container['invoice_number']) > 150)) {
            $invalid_properties[] = "invalid value for 'invoice_number', the character length must be smaller than or equal to 150.";
        }

        if ((strlen($this->container['invoice_number']) < 0)) {
            $invalid_properties[] = "invalid value for 'invoice_number', the character length must be bigger than or equal to 0.";
        }

        if ($this->container['invoice_date'] === null) {
            $invalid_properties[] = "'invoice_date' can't be null";
        }
        if ($this->container['invoice_amount'] === null) {
            $invalid_properties[] = "'invoice_amount' can't be null";
        }
        if ($this->container['invoice_description'] === null) {
            $invalid_properties[] = "'invoice_description' can't be null";
        }
        if ((strlen($this->container['invoice_description']) > 255)) {
            $invalid_properties[] = "invalid value for 'invoice_description', the character length must be smaller than or equal to 255.";
        }

        if ((strlen($this->container['invoice_description']) < 0)) {
            $invalid_properties[] = "invalid value for 'invoice_description', the character length must be bigger than or equal to 0.";
        }

        if ($this->container['invoice_pdf_submit_type'] === null) {
            $invalid_properties[] = "'invoice_pdf_submit_type' can't be null";
        }
        $allowed_values = ["URL", "BCC_EMAIL", "INCLUDED_DATA"];
        if (!in_array($this->container['invoice_pdf_submit_type'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'invoice_pdf_submit_type', must be one of #{allowed_values}.";
        }

        if (!is_null($this->container['invoice_pdf_url']) && (strlen($this->container['invoice_pdf_url']) > 511)) {
            $invalid_properties[] = "invalid value for 'invoice_pdf_url', the character length must be smaller than or equal to 511.";
        }

        if (!is_null($this->container['invoice_pdf_url']) && (strlen($this->container['invoice_pdf_url']) < 0)) {
            $invalid_properties[] = "invalid value for 'invoice_pdf_url', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['invoice_pdf_from_email']) && (strlen($this->container['invoice_pdf_from_email']) > 127)) {
            $invalid_properties[] = "invalid value for 'invoice_pdf_from_email', the character length must be smaller than or equal to 127.";
        }

        if (!is_null($this->container['invoice_pdf_from_email']) && (strlen($this->container['invoice_pdf_from_email']) < 0)) {
            $invalid_properties[] = "invalid value for 'invoice_pdf_from_email', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['invoice_pdf_email_subject']) && (strlen($this->container['invoice_pdf_email_subject']) > 127)) {
            $invalid_properties[] = "invalid value for 'invoice_pdf_email_subject', the character length must be smaller than or equal to 127.";
        }

        if (!is_null($this->container['invoice_pdf_email_subject']) && (strlen($this->container['invoice_pdf_email_subject']) < 0)) {
            $invalid_properties[] = "invalid value for 'invoice_pdf_email_subject', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['extra_info']) && (strlen($this->container['extra_info']) > 2147483647)) {
            $invalid_properties[] = "invalid value for 'extra_info', the character length must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['extra_info']) && (strlen($this->container['extra_info']) < 0)) {
            $invalid_properties[] = "invalid value for 'extra_info', the character length must be bigger than or equal to 0.";
        }

        if ($this->container['culture_code'] === null) {
            $invalid_properties[] = "'culture_code' can't be null";
        }
        if ((strlen($this->container['culture_code']) > 5)) {
            $invalid_properties[] = "invalid value for 'culture_code', the character length must be smaller than or equal to 5.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['transaction_number'] === null) {
            return false;
        }
        if (strlen($this->container['transaction_number']) > 32) {
            return false;
        }
        if (strlen($this->container['transaction_number']) < 0) {
            return false;
        }
        if (!preg_match("/[a-fA-F0-9]{32}/", $this->container['transaction_number'])) {
            return false;
        }
        if ($this->container['invoice_number'] === null) {
            return false;
        }
        if (strlen($this->container['invoice_number']) > 150) {
            return false;
        }
        if (strlen($this->container['invoice_number']) < 0) {
            return false;
        }
        if ($this->container['invoice_date'] === null) {
            return false;
        }
        if ($this->container['invoice_amount'] === null) {
            return false;
        }
        if ($this->container['invoice_description'] === null) {
            return false;
        }
        if (strlen($this->container['invoice_description']) > 255) {
            return false;
        }
        if (strlen($this->container['invoice_description']) < 0) {
            return false;
        }
        if ($this->container['invoice_pdf_submit_type'] === null) {
            return false;
        }
        $allowed_values = ["URL", "BCC_EMAIL", "INCLUDED_DATA"];
        if (!in_array($this->container['invoice_pdf_submit_type'], $allowed_values)) {
            return false;
        }
        if (strlen($this->container['invoice_pdf_url']) > 511) {
            return false;
        }
        if (strlen($this->container['invoice_pdf_url']) < 0) {
            return false;
        }
        if (strlen($this->container['invoice_pdf_from_email']) > 127) {
            return false;
        }
        if (strlen($this->container['invoice_pdf_from_email']) < 0) {
            return false;
        }
        if (strlen($this->container['invoice_pdf_email_subject']) > 127) {
            return false;
        }
        if (strlen($this->container['invoice_pdf_email_subject']) < 0) {
            return false;
        }
        if (strlen($this->container['extra_info']) > 2147483647) {
            return false;
        }
        if (strlen($this->container['extra_info']) < 0) {
            return false;
        }
        if ($this->container['culture_code'] === null) {
            return false;
        }
        if (strlen($this->container['culture_code']) > 5) {
            return false;
        }
        if (strlen($this->container['culture_code']) < 0) {
            return false;
        }
        return true;
    }


    /**
     * Gets transaction_number
     * @return string
     */
    public function getTransactionNumber()
    {
        return $this->container['transaction_number'];
    }

    /**
     * Sets transaction_number
     * @param string $transaction_number
     * @return $this
     */
    public function setTransactionNumber($transaction_number)
    {
        if ((strlen($transaction_number) > 32)) {
            throw new \InvalidArgumentException('invalid length for $transaction_number when calling InvoiceRequestV2Model., must be smaller than or equal to 32.');
        }
        if ((strlen($transaction_number) < 0)) {
            throw new \InvalidArgumentException('invalid length for $transaction_number when calling InvoiceRequestV2Model., must be bigger than or equal to 0.');
        }
        if ((!preg_match("/[a-fA-F0-9]{32}/", $transaction_number))) {
            throw new \InvalidArgumentException("invalid value for $transaction_number when calling InvoiceRequestV2Model., must conform to the pattern /[a-fA-F0-9]{32}/.");
        }

        $this->container['transaction_number'] = $transaction_number;

        return $this;
    }

    /**
     * Gets invoice_number
     * @return string
     */
    public function getInvoiceNumber()
    {
        return $this->container['invoice_number'];
    }

    /**
     * Sets invoice_number
     * @param string $invoice_number
     * @return $this
     */
    public function setInvoiceNumber($invoice_number)
    {
        if ((strlen($invoice_number) > 150)) {
            throw new \InvalidArgumentException('invalid length for $invoice_number when calling InvoiceRequestV2Model., must be smaller than or equal to 150.');
        }
        if ((strlen($invoice_number) < 0)) {
            throw new \InvalidArgumentException('invalid length for $invoice_number when calling InvoiceRequestV2Model., must be bigger than or equal to 0.');
        }

        $this->container['invoice_number'] = $invoice_number;

        return $this;
    }

    /**
     * Gets invoice_date
     * @return \DateTime
     */
    public function getInvoiceDate()
    {
        return $this->container['invoice_date'];
    }

    /**
     * Sets invoice_date
     * @param \DateTime $invoice_date
     * @return $this
     */
    public function setInvoiceDate($invoice_date)
    {
        $this->container['invoice_date'] = $invoice_date;

        return $this;
    }

    /**
     * Gets invoice_amount
     * @return int
     */
    public function getInvoiceAmount()
    {
        return $this->container['invoice_amount'];
    }

    /**
     * Sets invoice_amount
     * @param int $invoice_amount
     * @return $this
     */
    public function setInvoiceAmount($invoice_amount)
    {
        $this->container['invoice_amount'] = $invoice_amount;

        return $this;
    }

    /**
     * Gets invoice_description
     * @return string
     */
    public function getInvoiceDescription()
    {
        return $this->container['invoice_description'];
    }

    /**
     * Sets invoice_description
     * @param string $invoice_description
     * @return $this
     */
    public function setInvoiceDescription($invoice_description)
    {
        if ((strlen($invoice_description) > 255)) {
            throw new \InvalidArgumentException('invalid length for $invoice_description when calling InvoiceRequestV2Model., must be smaller than or equal to 255.');
        }
        if ((strlen($invoice_description) < 0)) {
            throw new \InvalidArgumentException('invalid length for $invoice_description when calling InvoiceRequestV2Model., must be bigger than or equal to 0.');
        }

        $this->container['invoice_description'] = $invoice_description;

        return $this;
    }

    /**
     * Gets invoice_pdf_submit_type
     * @return string
     */
    public function getInvoicePdfSubmitType()
    {
        return $this->container['invoice_pdf_submit_type'];
    }

    /**
     * Sets invoice_pdf_submit_type
     * @param string $invoice_pdf_submit_type
     * @return $this
     */
    public function setInvoicePdfSubmitType($invoice_pdf_submit_type)
    {
        $allowed_values = array('URL', 'BCC_EMAIL', 'INCLUDED_DATA');
        if ((!in_array($invoice_pdf_submit_type, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'invoice_pdf_submit_type', must be one of 'URL', 'BCC_EMAIL', 'INCLUDED_DATA'");
        }
        $this->container['invoice_pdf_submit_type'] = $invoice_pdf_submit_type;

        return $this;
    }

    /**
     * Gets invoice_pdf_url
     * @return string
     */
    public function getInvoicePdfUrl()
    {
        return $this->container['invoice_pdf_url'];
    }

    /**
     * Sets invoice_pdf_url
     * @param string $invoice_pdf_url
     * @return $this
     */
    public function setInvoicePdfUrl($invoice_pdf_url)
    {
        if (!is_null($invoice_pdf_url) && (strlen($invoice_pdf_url) > 511)) {
            throw new \InvalidArgumentException('invalid length for $invoice_pdf_url when calling InvoiceRequestV2Model., must be smaller than or equal to 511.');
        }
        if (!is_null($invoice_pdf_url) && (strlen($invoice_pdf_url) < 0)) {
            throw new \InvalidArgumentException('invalid length for $invoice_pdf_url when calling InvoiceRequestV2Model., must be bigger than or equal to 0.');
        }

        $this->container['invoice_pdf_url'] = $invoice_pdf_url;

        return $this;
    }

    /**
     * Gets invoice_pdf_email_sent_date
     * @return \DateTime
     */
    public function getInvoicePdfEmailSentDate()
    {
        return $this->container['invoice_pdf_email_sent_date'];
    }

    /**
     * Sets invoice_pdf_email_sent_date
     * @param \DateTime $invoice_pdf_email_sent_date
     * @return $this
     */
    public function setInvoicePdfEmailSentDate($invoice_pdf_email_sent_date)
    {
        $this->container['invoice_pdf_email_sent_date'] = $invoice_pdf_email_sent_date;

        return $this;
    }

    /**
     * Gets invoice_pdf_from_email
     * @return string
     */
    public function getInvoicePdfFromEmail()
    {
        return $this->container['invoice_pdf_from_email'];
    }

    /**
     * Sets invoice_pdf_from_email
     * @param string $invoice_pdf_from_email
     * @return $this
     */
    public function setInvoicePdfFromEmail($invoice_pdf_from_email)
    {
        if (!is_null($invoice_pdf_from_email) && (strlen($invoice_pdf_from_email) > 127)) {
            throw new \InvalidArgumentException('invalid length for $invoice_pdf_from_email when calling InvoiceRequestV2Model., must be smaller than or equal to 127.');
        }
        if (!is_null($invoice_pdf_from_email) && (strlen($invoice_pdf_from_email) < 0)) {
            throw new \InvalidArgumentException('invalid length for $invoice_pdf_from_email when calling InvoiceRequestV2Model., must be bigger than or equal to 0.');
        }

        $this->container['invoice_pdf_from_email'] = $invoice_pdf_from_email;

        return $this;
    }

    /**
     * Gets invoice_pdf_email_subject
     * @return string
     */
    public function getInvoicePdfEmailSubject()
    {
        return $this->container['invoice_pdf_email_subject'];
    }

    /**
     * Sets invoice_pdf_email_subject
     * @param string $invoice_pdf_email_subject
     * @return $this
     */
    public function setInvoicePdfEmailSubject($invoice_pdf_email_subject)
    {
        if (!is_null($invoice_pdf_email_subject) && (strlen($invoice_pdf_email_subject) > 127)) {
            throw new \InvalidArgumentException('invalid length for $invoice_pdf_email_subject when calling InvoiceRequestV2Model., must be smaller than or equal to 127.');
        }
        if (!is_null($invoice_pdf_email_subject) && (strlen($invoice_pdf_email_subject) < 0)) {
            throw new \InvalidArgumentException('invalid length for $invoice_pdf_email_subject when calling InvoiceRequestV2Model., must be bigger than or equal to 0.');
        }

        $this->container['invoice_pdf_email_subject'] = $invoice_pdf_email_subject;

        return $this;
    }

    /**
     * Gets extra_info
     * @return string
     */
    public function getExtraInfo()
    {
        return $this->container['extra_info'];
    }

    /**
     * Sets extra_info
     * @param string $extra_info
     * @return $this
     */
    public function setExtraInfo($extra_info)
    {
        if (!is_null($extra_info) && (strlen($extra_info) > 2147483647)) {
            throw new \InvalidArgumentException('invalid length for $extra_info when calling InvoiceRequestV2Model., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($extra_info) && (strlen($extra_info) < 0)) {
            throw new \InvalidArgumentException('invalid length for $extra_info when calling InvoiceRequestV2Model., must be bigger than or equal to 0.');
        }

        $this->container['extra_info'] = $extra_info;

        return $this;
    }

    /**
     * Gets culture_code
     * @return string
     */
    public function getCultureCode()
    {
        return $this->container['culture_code'];
    }

    /**
     * Sets culture_code
     * @param string $culture_code
     * @return $this
     */
    public function setCultureCode($culture_code)
    {
        if ((strlen($culture_code) > 5)) {
            throw new \InvalidArgumentException('invalid length for $culture_code when calling InvoiceRequestV2Model., must be smaller than or equal to 5.');
        }
        if ((strlen($culture_code) < 0)) {
            throw new \InvalidArgumentException('invalid length for $culture_code when calling InvoiceRequestV2Model., must be bigger than or equal to 0.');
        }

        $this->container['culture_code'] = $culture_code;

        return $this;
    }

    /**
     * Gets invoice_pdf_data
     * @return \Swagger\Client\Model\InvoicePdfDataModel
     */
    public function getInvoicePdfData()
    {
        return $this->container['invoice_pdf_data'];
    }

    /**
     * Sets invoice_pdf_data
     * @param \Swagger\Client\Model\InvoicePdfDataModel $invoice_pdf_data
     * @return $this
     */
    public function setInvoicePdfData($invoice_pdf_data)
    {
        $this->container['invoice_pdf_data'] = $invoice_pdf_data;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        $objSer = new Tritacv2_ObjectSerializer();
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode($objSer->sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode($objSer->sanitizeForSerialization($this));
    }
}
